### PR TITLE
Test toppage

### PR DESCRIPTION
**Pull request by hogehiga**
Some of https://trello.com/c/wLSxOiDS/60-- .

### CODE REVIEW

**Comment by hogehiga** [comment]
@yuya-painapo Sorry, please set environment variables NICOADD and NICOPASS in Travis-CI settings to pass test.

How to set enviroment variables in Travis-CI: 
http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by yuya-painapo** [comment]
追加しました！
ログとして表示しない設定にしてます。

**Comment by hogehiga** [comment]
Seem not set environment variables NICOADD and NICOPASS.

If environment variables set, Travis-CI's log output such as line 89-90 at https://travis-ci.org/hogehiga/want_to/builds/86355530 .

But that's not found in https://travis-ci.org/yuya-painapo/want_to/builds/86355554 .

**Comment by hogehiga** [comment]
Hmm...
Settings seem to be finished at https://travis-ci.org/yuya-painapo/want_to/settings .
I wonder what is happening...

**Comment by hogehiga** [comment]
I understood that.

http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

**Pull request closed without merging**
